# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: beredzhe <beredzhe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/12 21:56:28 by beredzhe          #+#    #+#              #
#    Updated: 2023/11/12 22:35:16 by beredzhe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FILES = display_file.c

.PHONY: all clean fclean

all:
	@gcc -Wall -Wextra -Werror -o $(NAME) $(FILES)

clean:
	@rm -f *.o

fclean: clean
	@rm -f $(NAME)